component System_error4 {
	def main(arg: Array<string>) -> int {
		foo1();
		return 0;
	}
	def foo1() { foo2(); }
	def foo2() { foo3(); }
	def foo3() {
		System.error("SystemError", "with a message");
	}
}
